apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    dashboards: grafana
  name: grafana
spec:
  config:
    auth.anonymous:
      enabled: "True"
    auth:
      disable_login_form: "False"
      disable_signout_menu: "True"
    auth.basic:
      enabled: "True"
    log:
      mode: console
    security:
      admin_password: secret
      admin_user: root
  service:
    spec:
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: grafana-http
  client:
    preferIngress: false
  version: 10.4.3
