apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./grafana/subscription.yaml
  - ./grafana/grafana.yaml
  - ./grafana/dashboards.yaml

configMapGenerator:
  - files:
    - ./grafana/dashboards/grafana-dashboard-istio-workload.json
    name: istio-workload
    namespace: monitoring
    options:
        disableNameSuffixHash: true
