apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: {{ include "echo-api.name" . }}-allow-all
  labels:
    {{- include "echo-api.labels" . | nindent 4 }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ include "echo-api.name" . }}
  rules:
    authentication:
