{
 "title": "MGC SRE Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Statuses",
   "type": "stat",
   "description": "Shows the number of pods by status in the selected namespace. Note this is an 'Instant' value i.e. it uses the latest value instead of querying over a range.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{exported_namespace=~\"$namespace\"}) by(phase)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{exported_namespace=~\"$namespace\"}[30m]))"
    }
   ]
  },
  {
   "title": "Pods Restarted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(kube_pod_container_status_restarts_total{exported_namespace=~\"$namespace\"}[30m]) > 0 )",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Shows the total number of Goroutines by pod in the selected namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Shows pod CPU usage for each pod in the namespace. If set, pod CPU requests and limits are also shown. The legend includes a suffix of the pod name.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[1m])) by(pod)",
     "legendFormat": "CPU Usage {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"cpu\"}",
     "legendFormat": "CPU Requests {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=~\"$namespace\", resource=\"cpu\"}",
     "legendFormat": "CPU Limits {{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Shows pod memory usage in MiB (based on RSS) for each pod in the namespace. If set, pod memory requests and limits are also shown. The legend includes a suffix of the pod name.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "Pod Memory {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"memory\"}",
     "legendFormat": "Pod Memory Requests {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=~\"$namespace\", resource=\"memory\"}",
     "legendFormat": "Pod Memory Limits {{pod}}"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "timeseries",
   "description": "Shows the rate of resources being queued for processing by each controller in the selected namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{namespace=~\"$namespace\"}[5m])) by (name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "timeseries",
   "description": "Shows the queue size for each resource controller in the selected namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{namespace=~\"$namespace\"}[5m])) by (name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "timeseries",
   "description": "Shows the queue processing latency for each resource controller in the selected namespace.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{namespace=~\"$namespace\"}[$__range])) by (name, le))",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  }
 ]
}