apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ./thanos/manifests/thanos-query-deployment.yaml
  - ./thanos/manifests/thanos-query-service.yaml
  - ./thanos/manifests/thanos-query-serviceAccount.yaml
  - ./thanos/manifests/thanos-receive-ingestor-default-service.yaml
  - ./thanos/manifests/thanos-receive-ingestor-default-statefulSet.yaml
  - ./thanos/manifests/thanos-receive-ingestor-serviceAccount.yaml
  - ./thanos/manifests/thanos-receive-router-configmap.yaml
  - ./thanos/manifests/thanos-receive-router-deployment.yaml
  - ./thanos/manifests/thanos-receive-router-service.yaml
  - ./thanos/manifests/thanos-receive-router-serviceAccount.yaml
  - ./thanos/manifests/thanos-receive-auth-secret-config.yaml
  - ./thanos/manifests/thanos-ruler-service.yaml
  - ./thanos/manifests/thanos-ruler-serviceAccount.yaml
  - ./thanos/manifests/thanos-ruler-statefulset.yaml
  - ./grafana/datasource.yaml

patches:
  - target:
      kind: Service
      name: thanos-receive-router
    path: ./thanos/manifests/thanos-receive-router-skupper-patch.yaml
  - path: grafana/grafana-patch.yaml
