apiVersion: kuadrant.io/v1
kind: TLSPolicy
metadata:
  name: {{ include "ingress-gateway.name" . }}-tls-policy
spec:
  targetRef:
    name: {{ include "ingress-gateway.name" . }}
    group: gateway.networking.k8s.io
    kind: Gateway
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ include "ingress-gateway.name" . }}-lets-encrypt-issuer
