kind: Istio
apiVersion: sailoperator.io/v1alpha1
metadata:
  name: {{ include "istio.name" . }}
spec:
  version: {{ .Values.istio.version }}
  namespace: istio-system
  updateStrategy:
    type: InPlace

  # Disable autoscaling to reduce dev resources
  values:
    pilot:
      autoscaleEnabled: false